name: Test262

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Clone Test262
        run: git clone https://github.com/tc39/test262.git

      - name: Run Test262
        run: pnpm rollup -c src/scripts/rollup.config.js && node dist/scripts/test262.js
